spring.application.name=backend
spring.profiles.active=test
spring.jpa.open-in-view=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/.well-known/jwks.json

logging.level.root=DEBUG
logging.level.org.springframework=DEBUG